### ISSUE TITLE
SIZE_MAX not fixed by CFLAGS

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MacPython/atom-wheels#2]
The issue seen with atom on 3.6 was encountered also in https://github.com/conda-forge/atom-feedstock/pull/2 where setting CFLAGS fixed the issue. Here it fails. Should I set that value somewhere else ?

**Comment by matthew-brett** [comment]
I've tried a push just now with the fix I think you need - you need to use the `env_vars.sh` file.

**Comment by MatthieuDartiailh** [comment]
Oh ... I hope it will work.

**Comment by matthew-brett** [comment]
It didn't - I'm just trying a debug print to see what's happening : https://travis-ci.org/MacPython/atom-wheels/builds/339550077

**Comment by matthew-brett** [comment]
There was a bug in multibuild - https://github.com/matthew-brett/multibuild/pull/141 - it should be fixed in the current build : https://travis-ci.org/MacPython/atom-wheels/builds/339682192

**Comment by MatthieuDartiailh** [comment]
Thanks for fixing it @matthew-brett ! I will try to create release branches and push on PyPI next week-end or sometimes next week. Thanks for your help with this.
