### ISSUE TITLE
v0.4.1 not uploaded

### ISSUE THREAD

**Issue by MatthieuDartiailh** [MacPython/atom-wheels#3]
Looking at the Travis log the "secret API key" is missing. @matthew-brett how should I proceed to fix this ?

**Comment by MatthieuDartiailh** [comment]
Appveyor appears to be fine.

**Comment by MatthieuDartiailh** [comment]
ping @matthew-brett

**Comment by matthew-brett** [comment]
The key is there - I can see the uploads at https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com - could you say more about the problem?

**Comment by MatthieuDartiailh** [comment]
Only the windows package are there, and in the Travis the system complain about a missing key.

**Comment by MatthieuDartiailh** [comment]
As shown here https://travis-ci.org/MacPython/atom-wheels/jobs/345301200 (last line you have to unfold)

**Comment by matthew-brett** [comment]
Ah sorry - I've updated the key - seems to be working on master now.

**Comment by MatthieuDartiailh** [comment]
Thanks @matthew-brett ! I will try to upload to PyPI during the week.
